### ISSUE TITLE
adding scram unsetenv before gsissh was done bad

### ISSUE THREAD

**Issue by belforte** [dmwm/CRAB2#1124]
and crab -submit fails with:
2014-06-18 15:16:26,817 [DEBUG]     Execute command :
eval `scram unsetenv -sh`; gsissh  -o ControlMaster=auto -o ControlPath=/tmp/belforte/.ssh/ssh-link--959738357-vocms83.cern.ch -o BatchMode=yes -o StrictHostKeyChecking=no -o ForwardX11=no vocms83.cern.ch  "sleep 3600"
2014-06-18 15:16:26,859 [DEBUG]     Unexpected exception executing Submission operation : Traceback (most recent call last):
  File "/afs/cern.ch/work/b/belforte/MY_CRAB2/python/Boss.py", line 147, in submit
    task_sub =  self.schedSession().submit( taskId, jobsList,req )
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB_DEVEL/external/ProdCommon/BossLite/API/BossLiteAPISched.py", line 129, in submit
    self.scheduler.submit( task, requirements )
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB_DEVEL/external/ProdCommon/BossLite/Scheduler/Scheduler.py", line 62, in submit
    self.parameters['config'], self.parameters['service']\
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB_DEVEL/external/ProdCommon/BossLite/Scheduler/SchedulerRemoteglidein.py", line 67, in submit
    self.initializeGsissh(obj)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB_DEVEL/external/ProdCommon/BossLite/Scheduler/SchedulerRemoteglidein.py", line 897, in initializeGsissh
    bkgGsissh = subprocess.Popen(shlex.split(command))
  File "/afs/cern.ch/cms/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/afs/cern.ch/cms/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

2014-06-18 15:16:26,860 [DEBUG]     common.scheduler.submit exception. Job(s) possibly not submitted
2014-06-18 15:16:26,860 [DEBUG]     ERROR: Job not submitted

**Comment by belforte** [comment]
basically shlex does not like two commands with a ; in between.
will cut it short and use Popen(shell=True) instead.

**Comment by belforte** [comment]
fix is in bosslite/scheduler/schedulerRemoteglidein.py requires a new ProdCommon tag

**Comment by belforte** [comment]
need to do more cleanly, as it is now it screws up rsync invocation.
