### ISSUE TITLE
in 2_11_1_pre5 -submit 1 -GRID.se_black_list=T1,T2 gives error

### ISSUE THREAD

**Issue by belforte** [dmwm/CRAB2#1185]
belforte@lxplus0124/TESTCRAB> crab -submit 1 -GRID.se_black_list=T1,T2
crab:  Version 2.11.1_pre5 running on Tue Sep  9 14:42:51 2014 CET (12:42:51 UTC)

crab. Working options:
        scheduler           remoteglidein
        job type            CMSSW
        server              OFF
        working directory   /afs/cern.ch/work/b/belforte/TESTCRAB/crab_0_140909_133326/

Traceback (most recent call last):
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB_DEVEL/python/crab.py", line 938, in <module>
    crab.run()
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB_DEVEL/python/crab.py", line 871, in run
    if act in self.actions.keys(): self.actions[act].run()
  File "/afs/cern.ch/work/b/belforte/MY_CRAB2/python/Submitter.py", line 115, in run
    self.BuildJobList()
  File "/afs/cern.ch/work/b/belforte/MY_CRAB2/python/Submitter.py", line 72, in BuildJobList
    cleanedBlackWhiteList = cleanPsnListForBlackWhiteLists(job['dlsDestination'], self.seBlackList, self.seWhiteList)
  File "/afs/cern.ch/work/b/belforte/MY_CRAB2/python/NodeNameUtils.py", line 249, in cleanPsnListForBlackWhiteLists
    tmpList.remove(dest)
ValueError: list.remove(x): x not in list

**Comment by belforte** [comment]
also if put in crab.cfg
SE_black_list = T1,T2

**Comment by belforte** [comment]
can't reproduce this :-(

**Comment by belforte** [comment]
can reproduce it now with
datasetpath = /GenericTTbar/HC-CMSSW_5_3_1_START53_V5-v1/GEN-SIM-RECO
SE_black_list = T1,T2

**Comment by belforte** [comment]
indeed it does not fail if I put
datasetpath = /SingleMu/Run2012B-TOPMuPlusJets-22Jan2013-v1/AOD

interesting...

**Comment by belforte** [comment]
problem was due to attempt to remove a site twice if BlackList had "duplicates" like T1,T1_FR_CCIN2P3
