### ISSUE TITLE
crab 2_9_2 fails when doing -report on a MC dataset

### ISSUE THREAD

**Issue by belforte** [dmwm/CRAB2#947]
[...]
crab:  The summary file inputLumiSummaryOfTask.json about input run and lumi isn't created
Traceback (most recent call last):
  File "/gpfs/cms/software/CRAB/CRAB_2_9_2/python/crab.py", line 928, in <module>
    crab.run()
  File "/gpfs/cms/software/CRAB/CRAB_2_9_2/python/crab.py", line 865, in run
    if act in self.actions.keys(): self.actions[act].run()
  File "/gpfs/cms/software/CRAB/CRAB_2_9_2/python/Reporter.py", line 207, in run
    if (self.cfg_params.get('CMSSW.lumi_mask') == None) and (os.path.isfile(inputRunLumiFileName) == False or (os.path.isfile(inputRunLumiFileName) == True and os.path.getsize(inputRunLumiFileName) == 0)):
  File "/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_11/external/slc5_amd64_gcc462/bin/../../../../../../external/python/2.6.4/lib/python2.6/genericpath.py", line 29, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
(e qui esce)

**Comment by belforte** [comment]
replaced by #948  with better description
