### ISSUE TITLE
crab_2_9_2 report prints a traceback when using split by event

### ISSUE THREAD

**Issue by belforte** [dmwm/CRAB2#948]
the needed report file for luminosity is created, so there may not be any real error, but surely this is very confusing for users:

belforte@lxplus433/gdr> crab -report
crab:  Version 2.9.2 running on Wed Nov 27 17:04:10 2013 CET (16:04:10 UTC)

crab. Working options:
    scheduler           remoteglidein
    job type            CMSSW
    server              OFF
    working directory   /afs/cern.ch/user/b/belforte/w0/crabtest/gdr/crab_0_131127_170401/

crab:  --------------------
Dataset: /GenericTTbar/HC-CMSSW_5_3_1_START53_V5-v1/GEN-SIM-RECO
Local output: /afs/cern.ch/user/b/belforte/w0/crabtest/gdr/crab_0_131127_170401/res/
Total Events read: 0
Total Files read: 0
Total Jobs : 10
Luminosity section summary file: /afs/cern.ch/user/b/belforte/w0/crabtest/gdr/crab_0_131127_170401/res/lumiSummary.json
   # Jobs: Created:10

---

crab:  The summary file inputLumiSummaryOfTask.json about input run and lumi isn't created
Traceback (most recent call last):
  File "/afs/cern.ch/cms/ccs/wm/scripts/Crab/CRAB_2_9_2/python/crab.py", line 928, in <module>
    crab.run()
  File "/afs/cern.ch/cms/ccs/wm/scripts/Crab/CRAB_2_9_2/python/crab.py", line 865, in run
    if act in self.actions.keys(): self.actions[act].run()
  File "/afs/cern.ch/cms/ccs/wm/scripts/Crab/CRAB_2_9_2/python/Reporter.py", line 207, in run
    if (self.cfg_params.get('CMSSW.lumi_mask') == None) and (os.path.isfile(inputRunLumiFileName) == False or (os.path.isfile(inputRunLumiFileName) == True and os.path.getsize(inputRunLumiFileName) == 0)):
  File "/afs/cern.ch/cms/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_1/external/slc5_amd64_gcc462/bin/../../../../../../external/python/2.6.4/lib/python2.6/genericpath.py", line 29, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
belforte@lxplus433/gdr>

**Comment by belforte** [comment]
fix released in 2_10_1
